/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;


/**
 *
 * @author My PC
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        initTabPanel();   
    }
    public frmMain(boolean isAdmin) {
        initComponents();
        initTabPanel();   
    }

    private void initTabPanel() {
        //
        PanelRoom pnr = new PanelRoom();
        tbnPanel.addTab("ROOM", pnr);
        
        PanelSubject pns = new PanelSubject();
        tbnPanel.addTab("SUBJECT", pns);
        
        PanelTimeTable pntt = new PanelTimeTable();
        tbnPanel.addTab("TIME TABLE", pntt);
        
        PanelUser pnu = new PanelUser();
        tbnPanel.addTab("USERS", pnu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        tbnPanel = new javax.swing.JTabbedPane();
        menuMain = new javax.swing.JMenuBar();
        menuSystem = new javax.swing.JMenu();
        menuILogout = new javax.swing.JMenuItem();
        menuIExit = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuSystem.setText("System");

        menuILogout.setText("Logout");
        menuILogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuILogoutActionPerformed(evt);
            }
        });
        menuSystem.add(menuILogout);

        menuIExit.setText("Exit");
        menuIExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIExitActionPerformed(evt);
            }
        });
        menuSystem.add(menuIExit);

        menuMain.add(menuSystem);

        menuHelp.setText("Help");
        menuMain.add(menuHelp);

        setJMenuBar(menuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuIExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuIExitActionPerformed

    private void menuILogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuILogoutActionPerformed
        this.dispose();
        frmLogin login = new frmLogin();
        login.setVisible(true);
    }//GEN-LAST:event_menuILogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuIExit;
    private javax.swing.JMenuItem menuILogout;
    private javax.swing.JMenuBar menuMain;
    private javax.swing.JMenu menuSystem;
    private javax.swing.JTabbedPane tbnPanel;
    // End of variables declaration//GEN-END:variables
}
