/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;
import control.select.SelectallTimeTable;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.TimeTable;
/**
 *
 * @author VuDucCanh
 */
public class PanelTimeTable extends javax.swing.JPanel {

    /**
     * Creates new form PanelTimeTable
     */
    DefaultTableModel dtbm = new DefaultTableModel();
    public PanelTimeTable() {
        initComponents();
        LoadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public  void LoadTable()
    {
        List<TimeTable> list = new ArrayList<>();
        
        dtbm.addColumn("SUBJECT_ID");
        dtbm.addColumn("SUBJECT_NAME"); 
        dtbm.addColumn("MAX_STUDENTS");
        dtbm.addColumn("REGISTED");
        dtbm.addColumn("TIME_ID");
        try {
            list = SelectallTimeTable.SelectallTimeTable();
            for (TimeTable timeTable : list) {
                Vector v = new Vector();
                v.add(timeTable.getSUBJECT_ID());
                v.add(timeTable.getSUBJECT_NAME());
                v.add(timeTable.getMAX_STUDENTS());
                v.add(timeTable.getREGISTED());
                v.add(timeTable.getTIME_ID());
                dtbm.addRow(v);
            }
            jTable1.setModel(dtbm);
        } catch (SQLException ex) {
            Logger.getLogger(PanelRoom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
